---
title: "Selections"
---

```{r, include = FALSE}
library(readxl)
library(dplyr)
library(kableExtra)

# players names


names <- c("Drew", "Bob", "Curran", "Sully", "Ray", "Shaw", 
           "Coady", "Pa", "Hanley")

# selections ---------------------------------------------------------------


for (name in names) {
  my_data <- read_excel("files/Wolfpack World Cup Predictor 2022.xlsm", 
                        sheet = name, col_names = FALSE)
  
  
  # group match  ------------------------------------------------------
  
  
  group_selections <- my_data[, 1:8]
  
  remove_ind <- c(1:2, sapply(1:7, \(x) (9 * x):((9 * x) + 2)), 72:73)
  
  group_selections <- group_selections[-remove_ind, ]
  
  group_selections[, 9] <- ifelse(
    !is.na(group_selections[, 2]), "Home Win (+2)", 
    ifelse(!is.na(group_selections[, 3]), "Home Win",
           ifelse(!is.na(group_selections[, 4]), "Draw",
                  ifelse(!is.na(group_selections[, 5]), "Away Win",
                         ifelse(!is.na(group_selections[, 6]), "Away Win (+2)",
                                "NA"
                         )))))
  
  group_selections <- group_selections[, c(1, 7, 9)]
  
  colnames(group_selections) <- c("Home Team", "Away Team", "Prediction")
  
  group_selections$`Home Team`[group_selections$`Home Team`
                               == "Netrherlands"] = "Netherlands"
  
  group_selections$`Home Team`[group_selections$`Home Team`
                               == "Crotia"] = "Croatia"
  
  group_selections$`Home Team`[group_selections$`Home Team`
                               == "IR Iran"] = "Iran"
  
  group_selections$`Home Team`[group_selections$`Home Team`
                               == "Tunsia"] = "Tunisia"
  
  group_selections$`Home Team`[group_selections$`Home Team`
                               == "Switzgerald"] = "Switzerland"
  
  
  
  
  group_selections$`Away Team`[group_selections$`Away Team`
                               == "Netrherlands"] = "Netherlands"
  
  group_selections$`Away Team`[group_selections$`Away Team`
                               == "Crotia"] = "Croatia"
  
  group_selections$`Away Team`[group_selections$`Away Team`
                               == "IR Iran"] = "Iran"
  
  group_selections$`Away Team`[group_selections$`Away Team`
                               == "Tunsia"] = "Tunisia"
  
  group_selections$`Away Team`[group_selections$`Away Team`
                               == "Switzgerald"] = "Switzerland"
  
  fixtures_results <- read.csv("files/fixtures-results.csv")
  
  
  df <- left_join(fixtures_results, group_selections, by = c("Home.Team" = "Home Team",
                                                             "Away.Team" = "Away Team"))
  df$order <- 1:nrow(df)
  
  df$Result <- ifelse(
    df$Home.Score > df$Away.Score + 1, "Home Win (+2)",
    ifelse(df$Home.Score + 1 < df$Away.Score, "Away Win (+2)",
           ifelse(df$Home.Score > df$Away.Score, "Home Win",
                  ifelse(df$Home.Score < df$Away.Score, "Away Win",
                         ifelse(df$Home.Score == df$Away.Score, "Draw", 
                                "NA")))))
  
  group_selections <- left_join(group_selections, 
                                df[, c("Home.Team", "Away.Team", "Result", "order")],
                                by = c("Home Team" = "Home.Team",
                                       "Away Team" = "Away.Team"))
  group_selections <- group_selections[order(group_selections$order), 1:4]
  
  group_selections$Points <- ifelse(
    (group_selections$Prediction == group_selections$Result) & (group_selections$Prediction == "Home Win (+2)" | group_selections$Prediction == "Away Win (+2)"), 2, 
    ifelse(group_selections$Prediction == group_selections$Result, 1, 
           ifelse((group_selections$Prediction == "Home Win" & group_selections$Result == "Home Win (+2)") | 
                    (group_selections$Prediction == "Away Win" & group_selections$Result == "Away Win (+2)"), 1,
                  ifelse((group_selections$Prediction == "Home Win (+2)" & group_selections$Result == "Home Win") | 
                           (group_selections$Prediction == "Away Win (+2)" & group_selections$Result == "Away Win"), 0,
                         ifelse(group_selections$Prediction == "Home Win (+2)" | group_selections$Prediction == "Away Win (+2)", -1, 0
                         )))))
  
  
  assign(paste0(name, "_selection_gm"), group_selections)
  
  
  
  # group rank points -------------------------------------------------------
  
  group_standings <- my_data[-c(1:2, 7:11, 16:20, 25:29, 34:38, 43:47,
                                52:56, 61:65, 70:73), 9:10]
  colnames(group_standings) <- c("Position", "Team")
  group_standings$Group <- rep(c("A", "B", "C", "D", "E", "F", "G", "H"),
                               each = 4)
  assign(paste0(name, "_selection_gs"), group_standings)
}



```

## Selections {.tabset}

::: panel-tabset
## Drew

::: panel-tabset
## Matches

```{r echo=FALSE}
Drew_selection_gm %>%
  kbl() %>%
  kable_styling() %>% 
  row_spec(which(Drew_selection_gm$Points == 2),  background = "green") %>% 
  row_spec(which(Drew_selection_gm$Points == 1),  background = "lightgreen") %>% 
  row_spec(which(Drew_selection_gm$Points == 0),  background = "yellow") %>% 
  row_spec(which(Drew_selection_gm$Points == -1),  background = "red")
```

## Group Table

```{r echo=FALSE}
Drew_selection_gs[, c(2, 1)] %>%
  kbl() %>%
  kable_styling() %>%
  pack_rows("Group A", 1, 4) %>%
  pack_rows("Group B", 5, 8) %>%
  pack_rows("Group C", 9, 12) %>%
  pack_rows("Group D", 13, 16) %>%
  pack_rows("Group E", 17, 20) %>%
  pack_rows("Group F", 21, 24) %>%
  pack_rows("Group G", 25, 28) %>%
  pack_rows("Group H", 29, 32)
```
:::

## Bob
::: panel-tabset
## Matches

```{r echo=FALSE}
Bob_selection_gm %>%
  kbl() %>%
  kable_styling() %>% 
  row_spec(which(Bob_selection_gm$Points == 2),  background = "green") %>% 
  row_spec(which(Bob_selection_gm$Points == 1),  background = "lightgreen") %>% 
  row_spec(which(Bob_selection_gm$Points == 0),  background = "yellow") %>% 
  row_spec(which(Bob_selection_gm$Points == -1),  background = "red")
```

## Group Table

```{r echo=FALSE}

Bob_selection_gs[, c(2, 1)] %>%
  kbl() %>%
  kable_styling() %>%
  pack_rows("Group A", 1, 4) %>%
  pack_rows("Group B", 5, 8) %>%
  pack_rows("Group C", 9, 12) %>%
  pack_rows("Group D", 13, 16) %>%
  pack_rows("Group E", 17, 20) %>%
  pack_rows("Group F", 21, 24) %>%
  pack_rows("Group G", 25, 28) %>%
  pack_rows("Group H", 29, 32)
```
:::

## Curran
::: panel-tabset
## Matches

```{r echo=FALSE}
Curran_selection_gm %>%
  kbl() %>%
  kable_styling()%>% 
  row_spec(which(Curran_selection_gm$Points == 2),  background = "green") %>% 
  row_spec(which(Curran_selection_gm$Points == 1),  background = "lightgreen") %>% 
  row_spec(which(Curran_selection_gm$Points == 0),  background = "yellow") %>% 
  row_spec(which(Curran_selection_gm$Points == -1),  background = "red")
```

## Group Table

```{r echo=FALSE}

Curran_selection_gs[, c(2, 1)] %>%
  kbl() %>%
  kable_styling() %>%
  pack_rows("Group A", 1, 4) %>%
  pack_rows("Group B", 5, 8) %>%
  pack_rows("Group C", 9, 12) %>%
  pack_rows("Group D", 13, 16) %>%
  pack_rows("Group E", 17, 20) %>%
  pack_rows("Group F", 21, 24) %>%
  pack_rows("Group G", 25, 28) %>%
  pack_rows("Group H", 29, 32)
```
:::

## Sully
::: panel-tabset
## Matches

```{r echo=FALSE}
Sully_selection_gm %>%
  kbl() %>%
  kable_styling() %>% 
  row_spec(which(Sully_selection_gm$Points == 2),  background = "green") %>% 
  row_spec(which(Sully_selection_gm$Points == 1),  background = "lightgreen") %>% 
  row_spec(which(Sully_selection_gm$Points == 0),  background = "yellow") %>% 
  row_spec(which(Sully_selection_gm$Points == -1),  background = "red")
```

## Group Table

```{r echo=FALSE}

Sully_selection_gs[, c(2, 1)] %>%
  kbl() %>%
  kable_styling() %>%
  pack_rows("Group A", 1, 4) %>%
  pack_rows("Group B", 5, 8) %>%
  pack_rows("Group C", 9, 12) %>%
  pack_rows("Group D", 13, 16) %>%
  pack_rows("Group E", 17, 20) %>%
  pack_rows("Group F", 21, 24) %>%
  pack_rows("Group G", 25, 28) %>%
  pack_rows("Group H", 29, 32)
```
:::

## Ray
::: panel-tabset
## Matches

```{r echo=FALSE}
Ray_selection_gm %>%
  kbl() %>%
  kable_styling() %>% 
  row_spec(which(Ray_selection_gm$Points == 2),  background = "green") %>% 
  row_spec(which(Ray_selection_gm$Points == 1),  background = "lightgreen") %>% 
  row_spec(which(Ray_selection_gm$Points == 0),  background = "yellow") %>% 
  row_spec(which(Ray_selection_gm$Points == -1),  background = "red")
```

## Group Table

```{r echo=FALSE}

Ray_selection_gs[, c(2, 1)] %>%
  kbl() %>%
  kable_styling() %>%
  pack_rows("Group A", 1, 4) %>%
  pack_rows("Group B", 5, 8) %>%
  pack_rows("Group C", 9, 12) %>%
  pack_rows("Group D", 13, 16) %>%
  pack_rows("Group E", 17, 20) %>%
  pack_rows("Group F", 21, 24) %>%
  pack_rows("Group G", 25, 28) %>%
  pack_rows("Group H", 29, 32)
```
:::


## Shaw
::: panel-tabset
## Matches

```{r echo=FALSE}
Shaw_selection_gm %>%
  kbl() %>%
  kable_styling() %>% 
  row_spec(which(Shaw_selection_gm$Points == 2),  background = "green") %>% 
  row_spec(which(Shaw_selection_gm$Points == 1),  background = "lightgreen") %>% 
  row_spec(which(Shaw_selection_gm$Points == 0),  background = "yellow") %>% 
  row_spec(which(Shaw_selection_gm$Points == -1),  background = "red")
```

## Group Table

```{r echo=FALSE}

Shaw_selection_gs[, c(2, 1)] %>%
  kbl() %>%
  kable_styling() %>%
  pack_rows("Group A", 1, 4) %>%
  pack_rows("Group B", 5, 8) %>%
  pack_rows("Group C", 9, 12) %>%
  pack_rows("Group D", 13, 16) %>%
  pack_rows("Group E", 17, 20) %>%
  pack_rows("Group F", 21, 24) %>%
  pack_rows("Group G", 25, 28) %>%
  pack_rows("Group H", 29, 32)
```
:::


## Coady
::: panel-tabset
## Matches

```{r echo=FALSE}
Coady_selection_gm %>%
  kbl() %>%
  kable_styling() %>% 
  row_spec(which(Coady_selection_gm$Points == 2),  background = "green") %>% 
  row_spec(which(Coady_selection_gm$Points == 1),  background = "lightgreen") %>% 
  row_spec(which(Coady_selection_gm$Points == 0),  background = "yellow") %>% 
  row_spec(which(Coady_selection_gm$Points == -1),  background = "red")
```

## Group Table

```{r echo=FALSE}

Coady_selection_gs[, c(2, 1)] %>%
  kbl() %>%
  kable_styling() %>%
  pack_rows("Group A", 1, 4) %>%
  pack_rows("Group B", 5, 8) %>%
  pack_rows("Group C", 9, 12) %>%
  pack_rows("Group D", 13, 16) %>%
  pack_rows("Group E", 17, 20) %>%
  pack_rows("Group F", 21, 24) %>%
  pack_rows("Group G", 25, 28) %>%
  pack_rows("Group H", 29, 32)
```
:::


## Pa
::: panel-tabset
## Matches

```{r echo=FALSE}
Pa_selection_gm %>%
  kbl() %>%
  kable_styling() %>% 
  row_spec(which(Pa_selection_gm$Points == 2),  background = "green") %>% 
  row_spec(which(Pa_selection_gm$Points == 1),  background = "lightgreen") %>% 
  row_spec(which(Pa_selection_gm$Points == 0),  background = "yellow") %>% 
  row_spec(which(Pa_selection_gm$Points == -1),  background = "red")
```

## Group Table

```{r echo=FALSE}

Pa_selection_gs[, c(2, 1)] %>%
  kbl() %>%
  kable_styling() %>%
  pack_rows("Group A", 1, 4) %>%
  pack_rows("Group B", 5, 8) %>%
  pack_rows("Group C", 9, 12) %>%
  pack_rows("Group D", 13, 16) %>%
  pack_rows("Group E", 17, 20) %>%
  pack_rows("Group F", 21, 24) %>%
  pack_rows("Group G", 25, 28) %>%
  pack_rows("Group H", 29, 32)
```
:::

## Hanley
::: panel-tabset
## Matches

```{r echo=FALSE}
Hanley_selection_gm %>%
  kbl() %>%
  kable_styling() %>% 
  row_spec(which(Hanley_selection_gm$Points == 2),  background = "green") %>% 
  row_spec(which(Hanley_selection_gm$Points == 1),  background = "lightgreen") %>% 
  row_spec(which(Hanley_selection_gm$Points == 0),  background = "yellow") %>% 
  row_spec(which(Hanley_selection_gm$Points == -1),  background = "red")
```

## Group Table

```{r echo=FALSE}

Hanley_selection_gs[, c(2, 1)] %>%
  kbl() %>%
  kable_styling() %>%
  pack_rows("Group A", 1, 4) %>%
  pack_rows("Group B", 5, 8) %>%
  pack_rows("Group C", 9, 12) %>%
  pack_rows("Group D", 13, 16) %>%
  pack_rows("Group E", 17, 20) %>%
  pack_rows("Group F", 21, 24) %>%
  pack_rows("Group G", 25, 28) %>%
  pack_rows("Group H", 29, 32)
```
:::
:::
